Add url check api
wearecoarmot/crawling-ui pull request #11
Opened 2020-01-09 00:56 UTC by kuckjwi0928

### What is this PR for?
Add url check api

### Tasks
* [x] - url을 통하여 robots 스캔 후 사이트가 크롤링이 가능한지 확인해주는 api 기능 추가

### ScreenShots (Optional)

### Questions (Optional)

2020-01-09 01:11 UTC, flyingSquirrel-dev requested changes

2020-01-09 01:11 UTC, flyingSquirrel-dev commented on server/config.py
> +CHROME_DRIVER_PATH = '/Volumes/kuckjwi/util/chromedriver'
제가 경로를 잘 몰라서 그런데, 이 디렉토리는 어디에 있는건가요? :D

2020-01-09 01:11 UTC, flyingSquirrel-dev commented on server/crawling/views.py
> +            'message': 'Missing url parameter.',
이것도 제가 크롤러를 많이 만들어보지 못해서 하는 질문일 수 있고, falsy한 값을 준다는 것에서 큰 차이는 없지만..
error handling하실 때 content가 빈스트링이 가는게 좋을까요?

soup.find('body')의 return value의 type이 string이라면 빈스트링으로 주셔도 좋을 것 같은데, 혹시 <body /> 라는 DOM node를 리턴하는 거라면 null이라든지 이런 falsy값을 주시는게 차라리 어떨까여?

JS에서 DOM node를 찾지못하면 기본적으로 return value는 null이니까요!

2020-01-09 01:12 UTC, kuckjwi commented on server/config.py
> +CHROME_DRIVER_PATH = '/Volumes/kuckjwi/util/chromedriver'
앗 설정값을 안비워놨네요
이 값은 유저들의 각 드라이버 경로 값이 필요하므로 비워놓고 주석달겠습니다!

2020-01-09 01:16 UTC, kuckjwi0928 commented on server/config.py
> +CHROME_DRIVER_PATH = '/Volumes/kuckjwi/util/chromedriver'
이 디렉토리는 크롤링 시 각 유저의 드라이버 패스 설정 값인데 제가 비워놓지를 못했네요!

비워놓고 주석 달아놓겠습니다 :)

2020-01-09 01:17 UTC, kuckjwi0928 commented on server/crawling/views.py
> +            'message': 'Missing url parameter.',
실제로 서버측에서는 `node` 타입이 아닌 `str` 타입의 `dom string`을 리턴하게 되어있기에 프론트측에서 DomParser를 통한 제어가 필요하기에 혹여나하는 error를 방지하기위해 content를 빈 스트링으로 넘겨주게되었습니다!

2020-01-10 03:51 UTC, flyingSquirrel-dev approved these changes

2020-01-10 04:04 UTC, merged