Add i18next
wearecoarmot/crawling-ui pull request #6
Opened 2019-12-30 14:12 UTC by LeeKangHyun

### What is this PR for?
Add i18next

### Tasks
* [x] - Add i18next

### ScreenShots (Optional)

### Questions (Optional)

2019-12-30 14:30 UTC, kuckjwi0928 commented
@LeeKangHyun 
[Project-board](https://github.com/orgs/wearecoarmot/projects/1#card-31047728)
위의 링크에서 칸반보드에서 카드 작성하시면서 진행해주세요~

2019-12-31 01:07 UTC, flyingSquirrel-dev requested changes

2019-12-31 01:07 UTC, flyingSquirrel-dev commented on client/src/components/Loading/index.tsx
>    useEffect(() => {
빈 useEffect가 왜 있나요? 👀

2019-12-31 01:38 UTC, LeeKangHyun commented on client/src/components/Loading/index.tsx
>    useEffect(() => {
아직 `WIP`중인 작업 이였는데 `commit & push`가 된지 확인을 못했네요..
다음 작업때 수정해서 올리도록 하겠습니다 :)

2019-12-31 11:54 UTC, flyingSquirrel-dev approved these changes

2019-12-31 11:54 UTC, flyingSquirrel-dev approved these changes

2019-12-31 12:01 UTC, flyingSquirrel-dev approved these changes

2019-12-31 12:03 UTC, merged